import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./ui/Navbar.jsx";
import SideNavbar from "./ui/SideNavbar.jsx";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transform scale-95 origin-top-left m-0 p-0 w-[100vw]`}
      >
          <div>
            <Navbar/>
            <div className="flex">
              <SideNavbar />
              {children}
            </div>
          </div>
      </body>
    </html>
  );
}
